/**
 * Unit tests for parseOutreachMd.
 *
 * Imports describe/it/expect directly from "vitest" rather than relying
 * on globals — keeps the file typecheckable by `tsc --noEmit` (the
 * tsconfig has no `types: ["vitest/globals"]` reference, by design).
 *
 * Coverage target: ≥95% on parseOutreachMd.ts (CTO gate).
 */
import { describe, it, expect } from "vitest";
import { parseOutreachMd, nameToSlug } from "../parseOutreachMd";

/* ── A canonical, full-shape transcript fixture ─────────────── */

const FULL_TRANSCRIPT = `# Agora Debate: Test Person
**For:** Test Person (Test Co)
**Topic:** Should I raise prices or stay cheap?
**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu
**Generated:** 2026-04-22

---

## Round 1

### Niccolò Machiavelli

You must raise prices and reposition.

A second paragraph from Machiavelli.

### Marie Curie

The question is a measurement problem.

### Sun Tzu

The race to the bottom is already lost.

## Round 2

### Niccolò Machiavelli

I hold firm — strike now.

### Marie Curie

Run the experiment.

### Sun Tzu

Fracture the coalition first.

## Round 3

### Niccolò Machiavelli

I concede partially.

### Marie Curie

The single most important takeaway is measurement.

### Sun Tzu

Anchor outcomes are the repositioning.

---

## Council Consensus

### Consensus Points
All three agree the cheap-pricing identity is a trap.

Second paragraph reinforces this.

### Key Tensions
Sequencing vs. measurement vs. narrative.

### Recommended Action
Raise prices on new customers, run case studies in parallel.

### Immediate Next Steps
- Step 1 (This week) — Audit your customer base.
- Step 2 (Within 30 days) — Raise the list price.
- Step 3 (Within 60 days) — Publish a case study.

### Risk Factors
Credibility collapse if no ROI architecture exists yet.

---

*Generated by [Consult The Dead — The Agora](https://consultthedead.com/agora)*
`;

describe("nameToSlug", () => {
  it("maps the five canonical outreach minds", () => {
    expect(nameToSlug("Niccolò Machiavelli")).toBe("niccolo-machiavelli");
    expect(nameToSlug("Marie Curie")).toBe("marie-curie");
    expect(nameToSlug("Sun Tzu")).toBe("sun-tzu");
    expect(nameToSlug("Marcus Aurelius")).toBe("marcus-aurelius");
    expect(nameToSlug("Leonardo da Vinci")).toBe("leonardo-da-vinci");
  });

  it("is diacritic-insensitive", () => {
    expect(nameToSlug("Niccolo Machiavelli")).toBe("niccolo-machiavelli");
    expect(nameToSlug("NICCOLÒ MACHIAVELLI")).toBe("niccolo-machiavelli");
  });

  it("collapses inner whitespace", () => {
    expect(nameToSlug("  Marie   Curie  ")).toBe("marie-curie");
  });

  it("falls back to kebab-case for any other ALLOWED_SLUGS member", () => {
    // "Isaac Newton" is in ALLOWED_SLUGS but not in the override table —
    // proves the kebab-case fallback path is exercised.
    expect(nameToSlug("Isaac Newton")).toBe("isaac-newton");
    expect(nameToSlug("Ada Lovelace")).toBe("ada-lovelace");
  });

  it("throws on names not in the roster", () => {
    // Steve Jobs is now a valid slug (task c7400a14 added him to ALLOWED_SLUGS)
    expect(nameToSlug("Steve Jobs")).toBe("steve-jobs");
    expect(() => nameToSlug("Elon Musk")).toThrow(/Unknown mind name/);
    expect(() => nameToSlug("")).toThrow(/Unknown mind name/);
  });
});

describe("parseOutreachMd — happy path", () => {
  const parsed = parseOutreachMd(FULL_TRANSCRIPT);

  it("extracts the topic verbatim", () => {
    expect(parsed.topic).toBe("Should I raise prices or stay cheap?");
  });

  it("preserves council order (names + slugs in parallel)", () => {
    expect(parsed.mindNames).toEqual([
      "Niccolò Machiavelli",
      "Marie Curie",
      "Sun Tzu",
    ]);
    expect(parsed.mindSlugs).toEqual([
      "niccolo-machiavelli",
      "marie-curie",
      "sun-tzu",
    ]);
  });

  it("counts 3 rounds", () => {
    expect(parsed.rounds).toBe(3);
  });

  it("emits 9 turns (3 rounds × 3 minds) with correct shape", () => {
    expect(parsed.turns).toHaveLength(9);
    for (const t of parsed.turns) {
      expect(typeof t.mindSlug).toBe("string");
      expect(typeof t.mindName).toBe("string");
      expect(typeof t.round).toBe("number");
      expect(typeof t.content).toBe("string");
      expect(t.content.length).toBeGreaterThan(0);
    }
    expect(parsed.turns[0]).toMatchObject({
      mindSlug: "niccolo-machiavelli",
      mindName: "Niccolò Machiavelli",
      round: 1,
    });
    expect(parsed.turns[8]).toMatchObject({
      mindSlug: "sun-tzu",
      mindName: "Sun Tzu",
      round: 3,
    });
  });

  it("preserves multi-paragraph content with a single blank-line gap", () => {
    const r1Mach = parsed.turns.find(
      (t) => t.round === 1 && t.mindSlug === "niccolo-machiavelli",
    )!;
    expect(r1Mach.content).toContain("You must raise prices");
    expect(r1Mach.content).toContain("A second paragraph");
    // Exactly one blank line between the two paragraphs:
    expect(r1Mach.content).toMatch(/raise prices and reposition\.\n\nA second paragraph/);
  });

  it("populates every consensus field", () => {
    const c = parsed.consensus;
    expect(c.points).toContain("All three agree the cheap-pricing identity is a trap");
    expect(c.tensions).toContain("Sequencing vs. measurement vs. narrative");
    expect(c.action).toContain("Raise prices on new customers");
    expect(c.steps).toEqual([
      "Step 1 (This week) — Audit your customer base.",
      "Step 2 (Within 30 days) — Raise the list price.",
      "Step 3 (Within 60 days) — Publish a case study.",
    ]);
    expect(c.risks).toContain("Credibility collapse");
  });

  it("populates the *_summary fields with non-empty strings", () => {
    const c = parsed.consensus;
    expect(c.pointsSummary.length).toBeGreaterThan(0);
    expect(c.tensionsSummary.length).toBeGreaterThan(0);
    expect(c.actionSummary.length).toBeGreaterThan(0);
    expect(c.stepsSummary.length).toBeGreaterThan(0);
    expect(c.risksSummary.length).toBeGreaterThan(0);
    // Summary stays bounded — not the whole points blob:
    expect(c.pointsSummary.length).toBeLessThanOrEqual(190);
  });

  it("does not bleed the `*Generated by …*` attribution into consensus", () => {
    expect(parsed.consensus.risks).not.toContain("Generated by");
    expect(parsed.consensus.risks).not.toContain("consultthedead.com");
  });

  it("yields content the public-page hasUsableConsensus check accepts", () => {
    const c = parsed.consensus;
    // The /agora/a/[id] page guards on these three fields. Mirror that
    // shape here so a regression fails loudly in this suite first.
    expect(typeof c.points).toBe("string");
    expect(typeof c.action).toBe("string");
    expect(Array.isArray(c.steps)).toBe(true);
  });
});

describe("parseOutreachMd — robustness", () => {
  it("tolerates Windows line endings", () => {
    const crlf = FULL_TRANSCRIPT.replace(/\n/g, "\r\n");
    const parsed = parseOutreachMd(crlf);
    expect(parsed.topic).toBe("Should I raise prices or stay cheap?");
    expect(parsed.turns).toHaveLength(9);
  });

  it("trims surrounding whitespace on the topic and council line", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Topic:** Should I raise prices or stay cheap?",
      "**Topic:**   Should I raise prices or stay cheap?   ",
    );
    expect(parseOutreachMd(md).topic).toBe("Should I raise prices or stay cheap?");
  });

  it("accepts a 5-mind council (the pro-tier max)", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu",
      "**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu, Marcus Aurelius, Leonardo da Vinci",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.mindSlugs).toEqual([
      "niccolo-machiavelli",
      "marie-curie",
      "sun-tzu",
      "marcus-aurelius",
      "leonardo-da-vinci",
    ]);
  });

  it("handles a missing Immediate Next Steps section (steps = [])", () => {
    const md = FULL_TRANSCRIPT.replace(
      /### Immediate Next Steps\n[\s\S]*?(?=### Risk Factors)/,
      "",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.consensus.steps).toEqual([]);
    expect(parsed.consensus.stepsSummary).toBe("");
  });

  it("handles an asterisk-bullet step list", () => {
    const md = FULL_TRANSCRIPT.replace(
      /- Step 1 \(This week\) — Audit your customer base\./,
      "* Step 1 (This week) — Audit your customer base.",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.consensus.steps[0]).toBe(
      "Step 1 (This week) — Audit your customer base.",
    );
  });

  it("drops an empty turn (mind header followed by no content)", () => {
    const md = FULL_TRANSCRIPT.replace(
      "### Sun Tzu\n\nThe race to the bottom is already lost.",
      "### Sun Tzu\n\n",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.turns.find((t) => t.round === 1 && t.mindSlug === "sun-tzu")).toBeUndefined();
    // Other turns still parse:
    expect(parsed.turns.length).toBe(8);
  });

  it("collapses 3+ consecutive blank lines into a single paragraph break", () => {
    const md = FULL_TRANSCRIPT.replace(
      "### Marie Curie\n\nThe question is a measurement problem.",
      "### Marie Curie\n\nThe question is a measurement problem.\n\n\n\n\nExtra paragraph after gap.",
    );
    const parsed = parseOutreachMd(md);
    const turn = parsed.turns.find(
      (t) => t.round === 1 && t.mindSlug === "marie-curie",
    )!;
    expect(turn.content).not.toMatch(/\n{3,}/);
    expect(turn.content).toContain("Extra paragraph after gap.");
  });

  it("is case-insensitive on the Round and Council Consensus headers", () => {
    const md = FULL_TRANSCRIPT.replace(
      "## Council Consensus",
      "## COUNCIL CONSENSUS",
    ).replace("## Round 1", "## ROUND 1");
    const parsed = parseOutreachMd(md);
    expect(parsed.rounds).toBe(3);
    expect(parsed.consensus.points.length).toBeGreaterThan(0);
  });

  it("handles a long single-sentence consensus (forces ellipsis truncation)", () => {
    const longSentence =
      "All three minds agree on a long, comma-laden, no-period thread of reasoning that runs well past one hundred forty characters and just keeps going and going and going without any sentence boundary to anchor a clean clip";
    const md = FULL_TRANSCRIPT.replace(
      "All three agree the cheap-pricing identity is a trap.",
      longSentence,
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.consensus.pointsSummary.endsWith("…")).toBe(true);
  });

  it("clips at the first sentence boundary when one exists in the 140–180 char window", () => {
    // Sentence one is >140 chars and ends with a period; total > 140 so the
    // short-circuit `return t` doesn't fire. The boundary regex must match
    // within `t.slice(0, maxLen + 40)` and the sliced summary must end on a
    // period (no ellipsis).
    // sentenceOne must be > 140 chars (so the early-return doesn't fire)
    // AND fit inside the maxLen+40 = 180 char window so the regex finds
    // its terminal period.
    const sentenceOne =
      "All three minds agree the cheap pricing identity is a structurally fragile foothold and that any continued race to the bottom is a brand-killing trap.";
    expect(sentenceOne.length).toBeGreaterThan(140);
    expect(sentenceOne.length).toBeLessThan(180);
    const md = FULL_TRANSCRIPT.replace(
      "All three agree the cheap-pricing identity is a trap.",
      `${sentenceOne} The second sentence is long enough to be truncated and never appears in the summary.`,
    );
    const parsed = parseOutreachMd(md);
    const s = parsed.consensus.pointsSummary;
    expect(s.endsWith(".")).toBe(true);
    expect(s.endsWith("…")).toBe(false);
    expect(s).not.toContain("second sentence");
  });

  it("ignores `### subheading` lines that don't match a known consensus key", () => {
    // A foreign sub-header inside Council Consensus must reset currentKey
    // and discard the prose under it; the next recognized key picks up cleanly.
    const md = FULL_TRANSCRIPT.replace(
      "### Risk Factors\nCredibility collapse if no ROI architecture exists yet.",
      "### Footnotes\nThis stray text must NOT land in any consensus field.\n\n### Risk Factors\nCredibility collapse if no ROI architecture exists yet.",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.consensus.points).not.toContain("stray text");
    expect(parsed.consensus.tensions).not.toContain("stray text");
    expect(parsed.consensus.action).not.toContain("stray text");
    expect(parsed.consensus.risks).toContain("Credibility collapse");
    expect(parsed.consensus.risks).not.toContain("stray text");
  });

  it("ignores prose before the first ## Round section", () => {
    // Stray paragraph between header and Round 1 must not become a turn —
    // exercises the `mode === 'scan'` default branch.
    const md = FULL_TRANSCRIPT.replace(
      "---\n\n## Round 1",
      "---\n\nThis is editorial preamble that should be discarded.\n\n## Round 1",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.turns).toHaveLength(9);
    for (const t of parsed.turns) {
      expect(t.content).not.toContain("editorial preamble");
    }
  });

  it("ignores body lines that arrive before the first ### MindName in a round", () => {
    // Tests that lines after `## Round 1` but before any `### Mind` don't
    // crash the parser (they fall into the `if (currentTurn) …` else path).
    const md = FULL_TRANSCRIPT.replace(
      "## Round 1\n\n### Niccolò Machiavelli",
      "## Round 1\n\nIntroductory line with no mind header.\n\n### Niccolò Machiavelli",
    );
    const parsed = parseOutreachMd(md);
    expect(parsed.turns).toHaveLength(9);
    expect(parsed.turns[0].content).not.toContain("Introductory line");
  });
});

describe("parseOutreachMd — error cases", () => {
  it("throws when **Topic:** is missing", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Topic:** Should I raise prices or stay cheap?\n",
      "",
    );
    expect(() => parseOutreachMd(md)).toThrow(/Missing field: Topic/);
  });

  it("throws when **Council:** is missing", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu\n",
      "",
    );
    expect(() => parseOutreachMd(md)).toThrow(/Missing field: Council/);
  });

  it("throws on an empty Topic", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Topic:** Should I raise prices or stay cheap?",
      "**Topic:**   ",
    );
    expect(() => parseOutreachMd(md)).toThrow(/Topic is empty/);
  });

  it("throws on an empty Council line", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu",
      "**Council:**   ",
    );
    expect(() => parseOutreachMd(md)).toThrow(/Council line is empty/);
  });

  it("throws on a council member outside ALLOWED_SLUGS", () => {
    const md = FULL_TRANSCRIPT.replace(
      "**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu",
      "**Council:** Niccolò Machiavelli, Marie Curie, Elon Musk",
    );
    expect(() => parseOutreachMd(md)).toThrow(/Unknown mind name/);
  });
});
