/**
 * /agora/a/[id] — public, read-only debate page.
 *
 * This is the landing surface for every shared agon URL: the 30
 * outreach-email links seeded into the agons table, plus any url
 * users copy from their /agora "Share this agon" UI. It's the
 * primary distribution lever for the founder directive (100 paying
 * users by end of May) and the frontend half of GAP-03.
 *
 * Behavior:
 *   - Server component, no Clerk auth required.
 *   - Resolves `[id]` against the public-safe `share_id` lookup
 *     (db.getPublicAgonByShareId). The /api/library/[id] HTTP route
 *     exposes the same path; we go through the db client directly
 *     to skip a self-fetch and to keep the lookup tolerant of any
 *     future share_id format changes (e.g. seed slugs containing
 *     hyphens, which the format guard at the API edge currently
 *     filters out).
 *   - Renders Topic, Council mind cards, the agon transcript with
 *     per-mind color accents, the Council Consensus block (when
 *     present), and the optional research bibliography.
 *   - Footer reads "Generated by Consult The Dead — The Agora" with
 *     a "Run your own agon →" CTA back to /agora. The CTA forwards
 *     utm_campaign + utm_content from the incoming URL so the
 *     conversion-attribution chain survives the page boundary
 *     (marketing playbook §3 line 214).
 *   - notFound() on missing / invalid id, and on database errors
 *     (the user-visible 404 is friendlier than a 500 for a public
 *     share link — the server logs still capture the raw error).
 *   - OG/Twitter metadata is built from the topic via
 *     generateMetadata so previews render well on every social
 *     platform.
 *   - Print uses the existing globals.css @media print rules. The
 *     interactive CTA row is annotated data-print="hide" to keep
 *     the saved PDF clean. The Generated-by footer line is left
 *     visible in print so attribution survives a printed share.
 */
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { ShareCtaStrip, ShareCtaStyles } from "@/components/ShareCtaStrip";
import { db, type PublicAgonRecord } from "@/lib/db/client";
import {
  ALLOWED_SLUGS,
  SLUG_COLOR_VAR,
  getFramework,
  type FrameworkSlug,
} from "@/lib/frameworks";
import { buildOgImageUrl } from "@/lib/og-image-url";
import {
  SHARE_CTA_BUTTON_LABEL,
  SHARE_CTA_SUBLINE,
  SHARE_SOCIAL_PROOF_LINE,
  buildShareCtaHref,
} from "@/lib/share-cta-link";

import {
  buildShareDescription,
  extractHighlightInsight,
  groupTurnsByRound,
  hasUsableConsensus,
  normalizeResearch,
  normalizeTurns,
  toRoman,
} from "./lib";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SITE_ORIGIN = "https://www.consultthedead.com";

type RouteParams = { id: string };

type PageProps = {
  params: Promise<RouteParams>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
};

/* ────────────────────────────────────────────────────────────────
   Mind metadata helper

   The frameworks loader reads JSON from disk, which is acceptable
   on the server but expensive if we re-read on every render. We
   memoize a slug→{name, colorVar} map for the lifetime of the
   server process. Using ALLOWED_SLUGS as the source of truth lets
   us return a fallback for any stale slug stored in the DB (e.g.
   `albert-einstein` after the legal-review hide).
   ──────────────────────────────────────────────────────────────── */

interface MindMeta {
  slug: string;
  name: string;
  era: string;
  colorVar: string;
}

let mindMetaCache: Map<string, MindMeta> | null = null;

function getMindMetaMap(): Map<string, MindMeta> {
  if (mindMetaCache) return mindMetaCache;
  const map = new Map<string, MindMeta>();
  for (const slug of ALLOWED_SLUGS) {
    const fw = getFramework(slug);
    if (!fw) continue;
    map.set(slug, {
      slug,
      name: fw.meta.person ?? slug,
      era: fw.era ?? "",
      colorVar: SLUG_COLOR_VAR[slug as FrameworkSlug] ?? "var(--fg)",
    });
  }
  mindMetaCache = map;
  return map;
}

function lookupMind(slug: string): MindMeta {
  const meta = getMindMetaMap().get(slug);
  if (meta) return meta;
  // Fallback for any slug stored before legal-review hide or
  // outside the live roster — render the slug as-is so the page
  // never crashes on stale data.
  return {
    slug,
    name: slug
      .split("-")
      .map((p) => (p.length > 0 ? p[0].toUpperCase() + p.slice(1) : p))
      .join(" "),
    era: "",
    colorVar: "var(--fg)",
  };
}

/* ────────────────────────────────────────────────────────────────
   Metadata
   ──────────────────────────────────────────────────────────────── */

async function loadAgon(id: string): Promise<PublicAgonRecord | null> {
  if (!id || typeof id !== "string") return null;
  try {
    return await db.getPublicAgonByShareId(id);
  } catch {
    // DB errors should not crash metadata generation. The page
    // body will surface a 404 below; meta will fall back to a
    // generic title.
    return null;
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const agon = await loadAgon(id);
  if (!agon) {
    return {
      title: "Agon not found · Consult The Dead",
      robots: { index: false, follow: false },
    };
  }
  const description = buildShareDescription(agon.topic);
  const url = `${SITE_ORIGIN}/agora/a/${agon.share_id}`;
  const title = `Agon: ${truncateForTitle(agon.topic)}`;
  const image = buildOgImageUrl(agon.share_id);
  return {
    title,
    description,
    alternates: { canonical: url },
    robots: { index: true, follow: true },
    openGraph: {
      title,
      description,
      url,
      type: "article",
      siteName: "Consult The Dead",
      images: image ? [image] : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: image ? [image] : undefined,
    },
  };
}

function truncateForTitle(topic: string, maxLen = 70): string {
  const t = (topic ?? "").trim().replace(/\s+/g, " ");
  if (!t) return "Untitled";
  if (t.length <= maxLen) return t;
  return t.slice(0, maxLen - 1).trimEnd() + "…";
}

/* ────────────────────────────────────────────────────────────────
   Page
   ──────────────────────────────────────────────────────────────── */

export default async function PublicAgonPage({ params }: PageProps) {
  const { id } = await params;

  const agon = await loadAgon(id);
  if (!agon) notFound();

  // Always tag the CTA with the share-loop attribution so cold visitors
  // (direct link, no incoming UTMs) land on /agora with full tracking.
  // Using buildShareCtaHref (not buildAgoraCtaHref which only forwards
  // incoming UTMs) ensures every click from the share page is attributed
  // per GOAL_FOUNDER.md "every shared link is an acquisition unit".
  const ctaHref = buildShareCtaHref(agon.share_id);

  const turns = normalizeTurns(agon.turns);
  const grouped = groupTurnsByRound(turns);
  const research = normalizeResearch(agon.research ?? null);
  const consensus = hasUsableConsensus(agon.consensus) ? agon.consensus : null;
  const highlight = extractHighlightInsight(agon.consensus);

  const council = (agon.mind_slugs ?? []).map((s) => lookupMind(s));
  const shareUrl = `https://www.consultthedead.com/agora/a/${agon.share_id}`;

  return (
    <main
      style={{
        minHeight: "calc(100vh - 80px)",
        padding: "48px 24px 96px",
        background: "var(--bg)",
        color: "var(--fg)",
      }}
    >
      <div style={{ maxWidth: "1100px", margin: "0 auto" }}>
        {/* Responsive show/hide rules for the inline + sticky CTA
            variants. Rendered once per page so both <ShareCtaStrip>
            instances pick up the same media query. */}
        <ShareCtaStyles />
        <Header />

        {/* CTAs moved below the consensus block — a cold visitor lands here
            from HN/Twitter and needs to see the debate substance before any
            "begin your own agon" push. "Liked the verdict?" only makes sense
            after they've read it. The sticky bottom bar still carries the
            CTA above-the-fold on mobile. */}

        <Section label="The Question">
          <p
            style={{
              fontFamily: "var(--font-serif)",
              fontSize: "clamp(1.4rem, 3.2vw, 1.85rem)",
              fontStyle: "italic",
              lineHeight: 1.4,
              color: "var(--fg)",
              margin: 0,
              maxWidth: "62ch",
            }}
          >
            &ldquo;{agon.topic}&rdquo;
          </p>
          {/* One-line social-proof strip near the topic. The
              attribution line is also visible in print (kept on
              purpose so a saved PDF still names the source). */}
          <p
            data-social-proof="agon-share"
            style={{
              fontFamily: "var(--font-serif)",
              fontStyle: "italic",
              fontSize: "0.85rem",
              color: "var(--fg-faint)",
              margin: "14px 0 0",
            }}
          >
            {SHARE_SOCIAL_PROOF_LINE}
          </p>
        </Section>

        <Section label="Council">
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
              gap: "16px",
            }}
          >
            {council.map((mind) => (
              <CouncilCard key={mind.slug} mind={mind} />
            ))}
          </div>
        </Section>

        {research && (
          <Section label="Research Brief">
            {research.summary && (
              <div
                style={{
                  fontFamily: "var(--font-serif)",
                  fontSize: "1rem",
                  lineHeight: 1.65,
                  color: "var(--fg-dim)",
                  borderLeft: "2px solid var(--hairline)",
                  paddingLeft: "16px",
                  whiteSpace: "pre-wrap",
                  marginBottom: research.sources.length > 0 ? "20px" : 0,
                }}
              >
                {research.summary}
              </div>
            )}
            {research.sources.length > 0 && (
              <div data-print-block>
                <p
                  className="font-mono uppercase"
                  style={{
                    fontSize: "10px",
                    letterSpacing: "0.14em",
                    color: "var(--fg-faint)",
                    margin: "0 0 8px",
                  }}
                >
                  Sources
                </p>
                <ul style={{ paddingLeft: "20px", margin: 0 }}>
                  {research.sources.map((src, i) => (
                    <li
                      key={`${src.url}-${i}`}
                      style={{
                        fontFamily: "var(--font-serif)",
                        fontSize: "14px",
                        lineHeight: 1.55,
                        color: "var(--fg-dim)",
                        marginBottom: "6px",
                      }}
                    >
                      <a
                        href={src.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ color: "var(--fg-dim)" }}
                      >
                        {src.title}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </Section>
        )}

        {grouped.length > 0 && (
          <Section label="The Agon">
            <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
              {grouped.map(({ round, turns: roundTurns }, idx) => (
                <div
                  key={round}
                  data-print-block
                  style={{
                    borderTop: idx > 0 ? "1px solid var(--hairline)" : "none",
                    paddingTop: idx > 0 ? "36px" : "0",
                    marginBottom: "36px",
                  }}
                >
                  <div
                    className="font-mono uppercase"
                    style={{
                      fontSize: "11px",
                      letterSpacing: "0.15em",
                      color: "var(--fg-dim)",
                      marginBottom: "20px",
                    }}
                  >
                    Round {toRoman(round)}
                  </div>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "column",
                      gap: "24px",
                    }}
                  >
                    {roundTurns.map((t, i) => {
                      const mind = lookupMind(t.mindSlug);
                      return (
                        <div key={`${round}-${t.mindSlug}-${i}`} data-print-block>
                          <div
                            className="font-mono uppercase"
                            style={{
                              fontSize: "11px",
                              letterSpacing: "0.1em",
                              color: mind.colorVar,
                            }}
                          >
                            {t.mindName || mind.name}
                          </div>
                          <p
                            style={{
                              fontFamily: "var(--font-serif)",
                              fontSize: "16px",
                              lineHeight: 1.65,
                              marginTop: "10px",
                              whiteSpace: "pre-wrap",
                              color: "var(--fg)",
                            }}
                          >
                            {t.text}
                          </p>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          </Section>
        )}

        {consensus && (
          <Section label="Council Consensus">
            <ConsensusBlock id="consensus-points" title="Consensus Points">
              <p>{consensus.points}</p>
            </ConsensusBlock>
            <ConsensusBlock id="consensus-tensions" title="Live Tensions">
              <p>{consensus.tensions}</p>
            </ConsensusBlock>
            <ConsensusBlock id="consensus-action" title="Recommended Action">
              <p>{consensus.action}</p>
            </ConsensusBlock>
            {consensus.steps.length > 0 && (
              <ConsensusBlock id="consensus-steps" title="Immediate Next Steps">
                <ul style={{ paddingLeft: "20px", margin: 0 }}>
                  {consensus.steps.map((s, i) => (
                    <li key={i} style={{ marginBottom: "6px" }}>
                      {s}
                    </li>
                  ))}
                </ul>
              </ConsensusBlock>
            )}
            <ConsensusBlock id="consensus-risks" title="Risks">
              <p>{consensus.risks}</p>
            </ConsensusBlock>
          </Section>
        )}

        {/* CTAs — placed AFTER the consensus so a cold visitor has read the
            verdict before being asked to "begin your own agon." */}
        <ConversionLeadIn ctaHref={ctaHref} />

        {/* Inline share CTA strip. Hidden in print + on screens ≤720px
            (the sticky bar at the bottom carries the same message there
            to avoid stacking on mobile). */}
        <ShareCtaStrip shareId={agon.share_id} variant="inline" />

        {/* Highlight insight pull-quote — the most notable single
            takeaway from the council's consensus, surfaced near the
            bottom so readers leave with a clear hook. Hidden in print
            so the pull-quote box doesn't interrupt a clean PDF export.
            Only shown when the consensus has usable content. */}
        {highlight && (
          <div
            data-print="hide"
            style={{
              marginTop: "56px",
              padding: "28px 32px",
              background: "var(--surface)",
              border: "1px solid var(--hairline)",
              borderLeft: "4px solid var(--amber)",
              maxWidth: "860px",
            }}
          >
            <p
              className="font-mono"
              style={{
                fontSize: "9px",
                letterSpacing: "0.18em",
                textTransform: "uppercase",
                color: "var(--amber)",
                margin: "0 0 12px",
              }}
            >
              {highlight.label}
            </p>
            <p
              style={{
                fontFamily: "var(--font-serif)",
                fontSize: "clamp(1rem, 2.2vw, 1.25rem)",
                fontStyle: "italic",
                lineHeight: 1.6,
                color: "var(--fg)",
                margin: 0,
              }}
            >
              &ldquo;{highlight.text}&rdquo;
            </p>
          </div>
        )}

        {/* Generated-by line — visible in print on purpose so the
            attribution survives any printed/saved share. */}
        <div
          style={{
            marginTop: "96px",
            paddingTop: "24px",
            borderTop: "1px solid var(--hairline)",
            textAlign: "center",
          }}
        >
          <p
            style={{
              fontFamily: "var(--font-serif)",
              fontStyle: "italic",
              fontSize: "14px",
              color: "var(--fg-dim)",
              margin: 0,
            }}
          >
            Generated by{" "}
            <Link
              href={ctaHref}
              style={{
                color: "var(--fg-dim)",
                textDecoration: "underline",
                textDecorationStyle: "dotted",
              }}
            >
              Consult The Dead — The Agora
            </Link>
          </p>
        </div>

        {/* Next-step CTA block — hidden in print. Two actions:
            1. Begin your own agon (primary) — uses share-loop UTM so
               every cold visitor is attributed, matching the founder
               directive (GOAL_FOUNDER.md "begin your own agon").
            2. Share this agon (secondary — copies/opens the share URL) */}
        <div
          data-print="hide"
          style={{
            marginTop: "32px",
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "center",
            gap: "16px",
          }}
        >
          <Link
            href={ctaHref}
            data-cta="begin-your-own-agon"
            className="font-mono"
            style={{
              display: "inline-block",
              background: "#2a2018",
              color: "#f0ead8",
              border: "none",
              borderRadius: 0,
              fontSize: "12px",
              letterSpacing: "0.15em",
              textTransform: "uppercase",
              padding: "16px 36px",
              textDecoration: "none",
            }}
          >
            {SHARE_CTA_BUTTON_LABEL}
          </Link>
          <Link
            href={shareUrl}
            data-cta="share-this-agon"
            className="font-mono"
            style={{
              display: "inline-block",
              background: "transparent",
              color: "var(--fg-dim)",
              border: "1px solid var(--hairline)",
              borderRadius: 0,
              fontSize: "12px",
              letterSpacing: "0.15em",
              textTransform: "uppercase",
              padding: "16px 36px",
              textDecoration: "none",
            }}
          >
            Share this agon
          </Link>
        </div>
      </div>

      {/* Sticky bottom CTA bar — mobile only (≤720px). Hidden in
          print so it never obscures the agon transcript on a saved
          PDF. Sits outside the centered content wrapper so it spans
          the full viewport width. */}
      <ShareCtaStrip shareId={agon.share_id} variant="sticky" />
    </main>
  );
}

/* ────────────────────────────────────────────────────────────────
   Sub-components (server-only, no useState/useEffect)
   ──────────────────────────────────────────────────────────────── */

function Header() {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "baseline",
        paddingBottom: "16px",
        borderBottom: "1px solid var(--hairline)",
        marginBottom: "48px",
      }}
    >
      <span
        className="font-mono"
        style={{
          fontSize: "10px",
          letterSpacing: "0.2em",
          textTransform: "uppercase",
          color: "var(--fg-faint)",
        }}
      >
        The Agora · Public Transcript
      </span>
      <span
        className="font-mono"
        style={{
          fontSize: "10px",
          letterSpacing: "0.2em",
          textTransform: "uppercase",
          color: "var(--fg-dim)",
        }}
      >
        Read-only
      </span>
    </div>
  );
}

function ConversionLeadIn({ ctaHref }: { ctaHref: string }) {
  return (
    <aside
      data-cta="share-page-funnel-lead-in"
      data-print="hide"
      style={{
        marginBottom: "28px",
        padding: "22px 24px",
        background:
          "linear-gradient(180deg, rgba(42, 32, 24, 0.05), rgba(42, 32, 24, 0.02))",
        border: "1px solid var(--hairline)",
        borderLeft: "3px solid var(--amber)",
      }}
    >
      <div
        className="font-mono uppercase"
        style={{
          fontSize: "10px",
          letterSpacing: "0.2em",
          color: "var(--fg-faint)",
          marginBottom: "10px",
        }}
      >
        Read-only transcript
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0, 1fr) auto",
          gap: "18px",
          alignItems: "center",
        }}
      >
        <div>
          <h2
            style={{
              fontFamily: "var(--font-serif)",
              fontSize: "clamp(1.3rem, 2.8vw, 1.9rem)",
              lineHeight: 1.25,
              margin: 0,
              color: "var(--fg)",
            }}
          >
            Liked the verdict? Begin your own agon.
          </h2>
          <p
            style={{
              fontFamily: "var(--font-serif)",
              fontSize: "1rem",
              lineHeight: 1.6,
              color: "var(--fg-dim)",
              margin: "10px 0 0",
              maxWidth: "68ch",
            }}
          >
            This public transcript is read-only. Start a fresh council with
            three minds and keep the momentum going in under a minute.
          </p>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-start",
            gap: "8px",
          }}
        >
          <Link
            href={ctaHref}
            data-cta="share-page-begin-your-own-agon"
            className="font-mono"
            style={{
              display: "inline-block",
              background: "#2a2018",
              color: "#f0ead8",
              border: "none",
              borderRadius: 0,
              fontSize: "12px",
              letterSpacing: "0.15em",
              textTransform: "uppercase",
              padding: "14px 28px",
              textDecoration: "none",
              whiteSpace: "nowrap",
            }}
          >
            {SHARE_CTA_BUTTON_LABEL}
          </Link>
          <span
            className="font-mono"
            style={{
              fontSize: "10px",
              letterSpacing: "0.08em",
              color: "var(--fg-faint)",
              textTransform: "uppercase",
            }}
          >
            {SHARE_CTA_SUBLINE}
          </span>
        </div>
      </div>
    </aside>
  );
}

function Section({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <section style={{ marginBottom: "56px" }}>
      <p
        className="font-mono uppercase"
        style={{
          fontSize: "10px",
          letterSpacing: "0.2em",
          color: "var(--fg-faint)",
          margin: "0 0 18px",
        }}
      >
        {label}
      </p>
      {children}
    </section>
  );
}

function CouncilCard({ mind }: { mind: MindMeta }) {
  return (
    <div
      style={{
        background: "var(--surface)",
        border: "1px solid var(--hairline)",
        borderLeft: `3px solid ${mind.colorVar}`,
        padding: "16px 18px",
        display: "flex",
        flexDirection: "column",
        gap: "6px",
      }}
    >
      <div
        className="font-mono uppercase"
        style={{
          fontSize: "11px",
          letterSpacing: "0.12em",
          color: mind.colorVar,
        }}
      >
        {mind.name}
      </div>
      {mind.era && (
        <div
          className="font-mono"
          style={{
            fontSize: "10px",
            letterSpacing: "0.08em",
            color: "var(--fg-faint)",
            textTransform: "uppercase",
          }}
        >
          {mind.era}
        </div>
      )}
    </div>
  );
}

function ConsensusBlock({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div id={id} style={{ marginBottom: "28px" }} data-print-block>
      <div
        className="font-mono uppercase"
        style={{
          fontSize: "11px",
          letterSpacing: "0.1em",
          color: "var(--amber)",
          marginBottom: "8px",
        }}
      >
        {title}
      </div>
      <div
        style={{
          fontFamily: "var(--font-serif)",
          fontSize: "16px",
          lineHeight: 1.65,
          color: "var(--fg)",
        }}
      >
        {children}
      </div>
    </div>
  );
}
