/**
 * Unit tests for the pure helpers in seed-outreach-agons.ts.
 *
 * The script's `main()` reads from disk and writes to Postgres — those
 * are integration concerns and are intentionally NOT exercised here.
 * What we cover:
 *   - slugFromFilename: filename → slug contract
 *   - findDebatesDir:   probes both invocation locations correctly
 *   - buildSeedRow:     parses a real-shaped transcript into the row
 *                       payload that gets passed to the SQL layer
 *
 * Importing the module is safe because it has an `isInvokedDirectly`
 * guard around `main()` — `process.env.VITEST` is set when this suite
 * runs, so the guard short-circuits and no DB calls are issued.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { describe, it, expect } from "vitest";

import {
  buildSeedRow,
  findDebatesDir,
  slugFromFilename,
} from "../seed-outreach-agons";

describe("slugFromFilename", () => {
  it("strips a trailing .md", () => {
    expect(slugFromFilename("abhishek-chakravarty.md")).toBe(
      "abhishek-chakravarty",
    );
  });

  it("strips a trailing .MD (case-insensitive)", () => {
    expect(slugFromFilename("ALI-ROHDE.MD")).toBe("ALI-ROHDE");
  });

  it("returns the filename unchanged when there is no .md suffix", () => {
    expect(slugFromFilename("readme")).toBe("readme");
  });
});

describe("findDebatesDir", () => {
  it("finds the dir when invoked from the repo root", () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "seed-test-"));
    try {
      fs.mkdirSync(path.join(tmp, "docs", "outreach-debates"), {
        recursive: true,
      });
      expect(findDebatesDir(tmp)).toBe(
        path.resolve(tmp, "docs", "outreach-debates"),
      );
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("finds the dir when invoked from a sibling subdir (e.g. website/)", () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "seed-test-"));
    try {
      fs.mkdirSync(path.join(tmp, "docs", "outreach-debates"), {
        recursive: true,
      });
      fs.mkdirSync(path.join(tmp, "website"), { recursive: true });
      expect(findDebatesDir(path.join(tmp, "website"))).toBe(
        path.resolve(tmp, "docs", "outreach-debates"),
      );
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("throws a clear error when the dir is missing entirely", () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "seed-test-"));
    try {
      expect(() => findDebatesDir(tmp)).toThrow(/outreach-debates not found/);
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });
});

describe("buildSeedRow", () => {
  const FIXTURE_MD = `# Agora Debate: Test Person
**For:** Test Person (Test Co)
**Topic:** Should I raise prices or stay cheap?
**Council:** Niccolò Machiavelli, Marie Curie, Sun Tzu
**Generated:** 2026-04-22

---

## Round 1

### Niccolò Machiavelli

You must raise prices.

### Marie Curie

Measure first.

### Sun Tzu

Refuse the battle.

## Round 2

### Niccolò Machiavelli

Strike now.

### Marie Curie

Run the experiment.

### Sun Tzu

Fracture the coalition.

## Round 3

### Niccolò Machiavelli

Concede partially.

### Marie Curie

Measurement remains the takeaway.

### Sun Tzu

Anchor outcomes are the move.

---

## Council Consensus

### Consensus Points
All three agree the cheap-pricing identity is a trap.

### Key Tensions
Sequencing vs. measurement vs. narrative.

### Recommended Action
Raise prices on new customers; run case studies in parallel.

### Immediate Next Steps
- Step 1 — Audit your customer base.
- Step 2 — Raise the list price.
- Step 3 — Publish a case study.

### Risk Factors
Credibility collapse without ROI architecture.

---

*Generated by [Consult The Dead — The Agora](https://consultthedead.com/agora)*
`;

  const row = buildSeedRow("test-person", FIXTURE_MD);

  it("pins id and shareId to the slug", () => {
    expect(row.id).toBe("test-person");
    expect(row.shareId).toBe("test-person");
  });

  it("preserves topic and mind ordering", () => {
    expect(row.topic).toBe("Should I raise prices or stay cheap?");
    expect(row.mindSlugs).toEqual([
      "niccolo-machiavelli",
      "marie-curie",
      "sun-tzu",
    ]);
    expect(row.rounds).toBe(3);
  });

  it("formats mindSlugsLiteral as a Postgres TEXT[] literal", () => {
    expect(row.mindSlugsLiteral).toBe(
      "{niccolo-machiavelli,marie-curie,sun-tzu}",
    );
  });

  it("produces a JSON-parseable turns array of length 9", () => {
    const parsed = JSON.parse(row.turnsJson);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed).toHaveLength(9);
    expect(parsed[0]).toMatchObject({
      mindSlug: "niccolo-machiavelli",
      mindName: "Niccolò Machiavelli",
      round: 1,
    });
    expect(typeof parsed[0].content).toBe("string");
  });

  it("produces a JSON-parseable consensus with all five fields populated", () => {
    const parsed = JSON.parse(row.consensusJson);
    expect(typeof parsed.points).toBe("string");
    expect(typeof parsed.tensions).toBe("string");
    expect(typeof parsed.action).toBe("string");
    expect(Array.isArray(parsed.steps)).toBe(true);
    expect(parsed.steps).toHaveLength(3);
    expect(typeof parsed.risks).toBe("string");
    expect(parsed.points.length).toBeGreaterThan(0);
  });

  it("propagates parser errors (malformed transcript)", () => {
    expect(() => buildSeedRow("missing-topic", "no fields here")).toThrow(
      /Missing field: Topic/,
    );
  });
});
