import fs from 'fs'
import path from 'path'

const DEBATES_DIR = path.join(process.cwd(), 'content', 'debates')

export interface AdvisorSpeech {
  advisor: string
  content: string
}

export interface Round {
  number: number
  speeches: AdvisorSpeech[]
}

export interface ConsensusSection {
  title: string
  content: string
}

export interface Debate {
  slug: string
  name: string
  forContext: string
  topic: string
  council: string[]
  date: string
  rounds: Round[]
  consensus: ConsensusSection[]
}

function parseDebate(slug: string, raw: string): Debate {
  const lines = raw.split('\n')

  // Header: lines 0–4
  const name = lines[0].replace(/^# Agora Debate:\s*/, '').trim()
  const forLine = lines[1].replace(/^\*\*For:\*\*\s*/, '').trim()
  const topic = lines[2].replace(/^\*\*Topic:\*\*\s*/, '').trim()
  const councilLine = lines[3].replace(/^\*\*Council:\*\*\s*/, '').trim()
  const date = lines[4].replace(/^\*\*Generated:\*\*\s*/, '').trim()

  const forMatch = forLine.match(/^(.+?)\s+\((.+)\)$/)
  const forContext = forMatch ? `${forMatch[1]} — ${forMatch[2]}` : forLine
  const council = councilLine.split(',').map(s => s.trim())

  // Split body at horizontal rules
  const parts = raw.split(/^---$/m)
  const roundsBody = parts[1] ?? ''
  const consensusBody = parts[2] ?? ''

  // Parse rounds: ## Round N sections
  const roundChunks = roundsBody.split(/^## Round \d+/m).slice(1)
  const rounds: Round[] = roundChunks.map((chunk, i) => {
    const advisorChunks = chunk.split(/^### /m).slice(1)
    const speeches: AdvisorSpeech[] = advisorChunks.map(ac => {
      const nl = ac.indexOf('\n')
      const advisor = ac.slice(0, nl).trim()
      const content = ac.slice(nl).trim()
      return { advisor, content }
    })
    return { number: i + 1, speeches }
  })

  // Parse consensus: ## Council Consensus then ### subsections
  const afterHeader = consensusBody.replace(/^[\s\S]*?## Council Consensus/, '')
  const sectionChunks = afterHeader.split(/^### /m).slice(1)
  const consensus: ConsensusSection[] = sectionChunks.map(sc => {
    const nl = sc.indexOf('\n')
    const title = sc.slice(0, nl).trim()
    const content = sc.slice(nl).trim()
      .replace(/\n---\n[\s\S]*$/, '')  // strip trailing generated-by line
      .replace(/\*Generated by[\s\S]*$/, '')
      .trim()
    return { title, content }
  })

  return { slug, name, forContext, topic, council, date, rounds, consensus }
}

export function getAllDebateSlugs(): string[] {
  try {
    return fs.readdirSync(DEBATES_DIR)
      .filter(f => f.endsWith('.md'))
      .map(f => f.replace(/\.md$/, ''))
  } catch {
    return []
  }
}

export function getDebate(slug: string): Debate | null {
  try {
    const filePath = path.join(DEBATES_DIR, `${slug}.md`)
    const raw = fs.readFileSync(filePath, 'utf-8')
    return parseDebate(slug, raw)
  } catch {
    return null
  }
}
