/**
 * parseOutreachMd — convert a markdown debate transcript from
 * docs/outreach-debates/<slug>.md into the AgonRecord-shaped JSON the
 * agons table expects.
 *
 * Used by the one-shot seed script (website/scripts/seed-outreach-agons.ts)
 * that backfills 30 outreach debate transcripts so /agora/a/<slug>
 * resolves for every email recipient (per the marketing playbook).
 *
 * Why this lives in src/lib (not next to the script):
 *   - vitest's coverage `include` is rooted at `src/**`, so the parser is
 *     covered by the unit-test gate. Pure data shaping; no Node-only APIs.
 *   - The script depends on it, but the parser is independently useful
 *     (e.g. preview tooling, future content pipelines).
 *
 * Markdown shape expected (see docs/outreach-debates/abhishek-chakravarty.md
 * for the canonical fixture):
 *
 *     # Agora Debate: <Recipient>
 *     **For:** ...
 *     **Topic:** <single-line topic>
 *     **Council:** <Mind1>, <Mind2>, <Mind3>[, <Mind4>, <Mind5>]
 *     **Generated:** <date>
 *
 *     ---
 *     ## Round 1
 *     ### <MindName>
 *     <paragraphs>
 *     ### <MindName>
 *     <paragraphs>
 *     ## Round 2
 *     ...
 *     ## Round 3
 *     ...
 *
 *     ---
 *     ## Council Consensus
 *     ### Consensus Points
 *     <paragraphs>
 *     ### Key Tensions
 *     <paragraphs>
 *     ### Recommended Action
 *     <paragraphs>
 *     ### Immediate Next Steps
 *     - Step 1 ... — ...
 *     - Step 2 ... — ...
 *     ### Risk Factors
 *     <paragraphs>
 *
 *     ---
 *     *Generated by [Consult The Dead — The Agora](...)*
 *
 * Robustness:
 *   - Throws when the required fields (Topic, Council) are missing — the
 *     seed script wants to fail loud rather than insert a half-empty row.
 *   - Tolerant of trailing/leading whitespace, blank lines inside turns,
 *     and the `---` horizontal rules between sections.
 *   - Mind names are mapped to FrameworkSlug via a small lookup table that
 *     covers every council member that actually appears in the 30 outreach
 *     transcripts. Anything outside that set is rejected so we never
 *     silently insert a row with a slug the /frameworks roster cannot
 *     render.
 */
import { ALLOWED_SLUGS, type FrameworkSlug } from "@/lib/frameworks";
import type { ConsensusResult } from "@/lib/agon/types";

/* ── Public types ──────────────────────────────────────────────── */

/**
 * Turn shape the seed-script writes into the `turns` JSONB column.
 *
 * Note the field is `content` (not `text`) — this matches the legacy
 * AgoraApp save shape and is the second branch handled by the public
 * page's `normalizeTurns` helper at /agora/a/[id]. Either field name
 * renders correctly; we keep `content` to be explicit that this row
 * was authored from a static transcript, not the live agon engine.
 */
export interface OutreachTurn {
  mindSlug: FrameworkSlug;
  mindName: string;
  round: number;
  content: string;
}

export interface OutreachAgonRecord {
  topic: string;
  /** Council mind slugs, in the order they appear on the Council line. */
  mindSlugs: FrameworkSlug[];
  /** Council mind display names, parallel to mindSlugs. */
  mindNames: string[];
  /** Number of rounds actually parsed (3 in every shipped transcript). */
  rounds: number;
  turns: OutreachTurn[];
  consensus: ConsensusResult;
}

/* ── Mind name → slug normalization ────────────────────────────── */

/**
 * Authoritative mapping for the names that appear in the 30 outreach
 * transcripts. Diacritic-insensitive on the lookup side — both
 * "Niccolò" and "Niccolo" hit the same entry.
 *
 * Adding a new mind here requires the slug to also exist in
 * lib/frameworks.ts ALLOWED_SLUGS; the runtime check at the bottom
 * of `nameToSlug` enforces that.
 */
const MIND_NAME_OVERRIDES: Record<string, FrameworkSlug> = {
  "niccolo machiavelli": "niccolo-machiavelli",
  "marie curie": "marie-curie",
  "sun tzu": "sun-tzu",
  "marcus aurelius": "marcus-aurelius",
  "leonardo da vinci": "leonardo-da-vinci",
};

/**
 * Strip combining diacritics and lowercase. Used so "Niccolò" and
 * "Niccolo" both resolve identically. Safe on inputs without any
 * combining marks.
 */
function normalizeName(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");
}

/**
 * Map a mind display name (as it appears in the Council line or a
 * `### Mind Name` round header) to the slug used by the frameworks
 * roster.
 *
 * Throws on names that aren't in the override table AND don't kebab
 * to a known slug — the seed script must fail loud rather than write
 * a row with a slug the public page can't render.
 */
export function nameToSlug(name: string): FrameworkSlug {
  const key = normalizeName(name);
  const override = MIND_NAME_OVERRIDES[key];
  if (override) return override;
  const kebab = key.replace(/\s+/g, "-");
  if ((ALLOWED_SLUGS as readonly string[]).includes(kebab)) {
    return kebab as FrameworkSlug;
  }
  throw new Error(`Unknown mind name: ${name}`);
}

/* ── Field readers ─────────────────────────────────────────────── */

function readField(lines: string[], label: string): string {
  const prefix = `**${label}:**`;
  for (const raw of lines) {
    const t = raw.trim();
    if (t.startsWith(prefix)) {
      return t.slice(prefix.length).trim();
    }
  }
  throw new Error(`Missing field: ${label}`);
}

/* ── Main parser ───────────────────────────────────────────────── */

const ROUND_RE = /^##\s+Round\s+(\d+)\s*$/i;
const COUNCIL_HEADER_RE = /^##\s+Council\s+Consensus\s*$/i;
const SUB_HEADER_RE = /^###\s+(.+?)\s*$/;
const HR_RE = /^---+\s*$/;

interface RoundBuilder {
  round: number;
  turns: { mindName: string; lines: string[] }[];
}

type ConsensusKey = "points" | "tensions" | "action" | "steps" | "risks";

const CONSENSUS_SUB_KEY: Record<string, ConsensusKey> = {
  "consensus points": "points",
  "key tensions": "tensions",
  "recommended action": "action",
  "immediate next steps": "steps",
  "risk factors": "risks",
};

export function parseOutreachMd(md: string): OutreachAgonRecord {
  const lines = md.split(/\r?\n/);

  const topic = readField(lines, "Topic");
  if (!topic) throw new Error("Topic is empty");
  const councilLine = readField(lines, "Council");
  const mindNames = councilLine
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  if (mindNames.length === 0) {
    throw new Error("Council line is empty");
  }
  const mindSlugs = mindNames.map(nameToSlug);

  // Walk for rounds + consensus sections.
  type Mode = "scan" | "round" | "consensus";
  let mode: Mode = "scan";
  const rounds: RoundBuilder[] = [];
  let currentRound: RoundBuilder | null = null;
  let currentTurn: { mindName: string; lines: string[] } | null = null;
  let currentKey: ConsensusKey | null = null;

  const consensus: Record<ConsensusKey, string[]> = {
    points: [],
    tensions: [],
    action: [],
    steps: [],
    risks: [],
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    const trimmed = line.trim();

    const roundMatch = trimmed.match(ROUND_RE);
    if (roundMatch) {
      currentTurn = null;
      currentRound = { round: Number(roundMatch[1]), turns: [] };
      rounds.push(currentRound);
      mode = "round";
      continue;
    }

    if (COUNCIL_HEADER_RE.test(trimmed)) {
      currentTurn = null;
      currentRound = null;
      currentKey = null;
      mode = "consensus";
      continue;
    }

    if (mode === "round") {
      const subMatch = trimmed.match(SUB_HEADER_RE);
      if (subMatch) {
        currentTurn = { mindName: subMatch[1].trim(), lines: [] };
        currentRound!.turns.push(currentTurn);
        continue;
      }
      if (HR_RE.test(trimmed)) continue;
      if (currentTurn) currentTurn.lines.push(line);
      continue;
    }

    if (mode === "consensus") {
      const subMatch = trimmed.match(SUB_HEADER_RE);
      if (subMatch) {
        const k = CONSENSUS_SUB_KEY[subMatch[1].trim().toLowerCase()];
        currentKey = k ?? null;
        continue;
      }
      if (HR_RE.test(trimmed)) {
        // Horizontal rule closes the consensus block — anything that
        // follows (e.g. the *Generated by …* attribution line) is not
        // part of the saved record.
        currentKey = null;
        continue;
      }
      if (currentKey) consensus[currentKey].push(line);
      continue;
    }
  }

  // Materialize turns
  const turns: OutreachTurn[] = [];
  for (const r of rounds) {
    for (const t of r.turns) {
      const content = collapseBlock(t.lines);
      if (!content) continue;
      turns.push({
        mindSlug: nameToSlug(t.mindName),
        mindName: t.mindName,
        round: r.round,
        content,
      });
    }
  }

  // Materialize consensus
  const stepsItems = parseStepsList(consensus.steps);

  const consensusOut: ConsensusResult = {
    points: collapseBlock(consensus.points),
    pointsSummary: summarize(collapseBlock(consensus.points)),
    tensions: collapseBlock(consensus.tensions),
    tensionsSummary: summarize(collapseBlock(consensus.tensions)),
    action: collapseBlock(consensus.action),
    actionSummary: summarize(collapseBlock(consensus.action)),
    steps: stepsItems,
    stepsSummary: stepsItems.length > 0 ? summarize(stepsItems[0]) : "",
    risks: collapseBlock(consensus.risks),
    risksSummary: summarize(collapseBlock(consensus.risks)),
  };

  return {
    topic,
    mindNames,
    mindSlugs,
    rounds: rounds.length,
    turns,
    consensus: consensusOut,
  };
}

/* ── Helpers ───────────────────────────────────────────────────── */

/**
 * Join paragraph lines back together, preserving blank-line paragraph
 * breaks but collapsing 3+ blank lines into a single break and
 * trimming surrounding whitespace.
 */
function collapseBlock(rawLines: string[]): string {
  return rawLines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Parse the `### Immediate Next Steps` bullet list. Accepts either
 * `- ` or `* ` bullets (we only emit `- ` today, but tolerate the
 * other in case future authors switch). Returns an empty array if
 * no bullet items are found.
 */
function parseStepsList(rawLines: string[]): string[] {
  const out: string[] = [];
  for (const raw of rawLines) {
    const t = raw.trim();
    const m = t.match(/^[-*]\s+(.+)$/);
    if (m) out.push(m[1].trim());
  }
  return out;
}

/**
 * Cheap summary builder. Tries to clip at the first sentence boundary
 * within `maxLen + 40`; otherwise hard-truncates with an ellipsis.
 * Returns the empty string when there's nothing presentable.
 */
function summarize(text: string, maxLen = 140): string {
  const t = text.replace(/\s+/g, " ").trim();
  if (!t) return "";
  if (t.length <= maxLen) return t;
  const window = t.slice(0, maxLen + 40);
  const m = window.match(/[.!?](?:\s|$)/);
  if (m && m.index !== undefined && m.index >= 30) {
    return window.slice(0, m.index + 1).trim();
  }
  return t.slice(0, maxLen - 1).trimEnd() + "…";
}
