/**
 * UTM link builder for the public /agora/a/<share_id> conversion CTA.
 *
 * Every visitor landing on a public agon page is an acquisition unit
 * (per GOAL_FOUNDER.md). The "Begin your own agon — 3 free debates
 * today" CTA on /agora/a/[id] is the primary conversion lever for
 * traffic arriving from outreach emails, Twitter shares, iMessage
 * previews, and any user-shared agon link.
 *
 * Contract (per task 9dcdbd1f):
 *
 *     /agora?utm_source=share
 *           &utm_campaign=agon_share
 *           &utm_content=<share_id>
 *
 * - utm_source = "share"          (every share-page CTA)
 * - utm_campaign = "agon_share"   (groups all share-driven traffic)
 * - utm_content = <share_id>      (which agon drove this conversion)
 *
 * Defaults are intentionally locked in so the public page calls the
 * helper with just the share_id; the optional override fields exist so
 * future variants (e.g. an A/B'd CTA copy) can carry a content tag
 * without changing the signature elsewhere.
 *
 * Pure — no React, no Next, no DB. Coverage gate is the only required
 * test for capsule 9ffb5a13 (share-cta-link.test.ts in __tests__).
 */

/**
 * Optional overrides for the share-CTA href.
 *
 * In the common case (server-rendered public agon page), only `shareId`
 * is supplied via the positional argument and this object is omitted.
 * The overrides exist to keep the helper testable and to allow future
 * funnel variants without forcing every caller through new positional
 * args.
 */
export interface ShareCtaHrefOptions {
  /** Override utm_source (default "share"). */
  utmSource?: string;
  /** Override utm_campaign (default "agon_share"). */
  utmCampaign?: string;
  /**
   * Override utm_content. Defaults to the `shareId` argument so every
   * share-CTA tags itself with the originating agon's slug.
   */
  utmContent?: string;
  /**
   * Pre-fill the topic on /agora when the visitor lands. Currently
   * unused by AgoraApp (which loads its own state) but reserved so a
   * future "Continue this debate" CTA variant can deep-link without
   * needing a second helper. Empty / unset → no `topic` query param.
   */
  topic?: string;
}

/**
 * Build the conversion CTA href for the public agon page.
 *
 * Returns a relative path (`/agora?...`) so the caller can drop it
 * straight into a `<Link href={...}>` without worrying about origin
 * — Next.js handles the resolve.
 *
 * Throws on missing `shareId` rather than silently producing a broken
 * URL. The render path is the only caller and a missing share_id is a
 * programming error.
 */
export function buildShareCtaHref(
  shareId: string,
  options: ShareCtaHrefOptions = {},
): string {
  if (!shareId || typeof shareId !== "string") {
    throw new Error("buildShareCtaHref: shareId is required");
  }
  const trimmedId = shareId.trim();
  if (!trimmedId) {
    throw new Error("buildShareCtaHref: shareId is required");
  }

  const utmSource = options.utmSource ?? "share";
  const utmCampaign = options.utmCampaign ?? "agon_share";
  const utmContent = options.utmContent ?? trimmedId;

  const params = new URLSearchParams();
  params.set("utm_source", utmSource);
  params.set("utm_campaign", utmCampaign);
  if (utmContent && utmContent.length > 0) {
    params.set("utm_content", utmContent);
  }
  if (typeof options.topic === "string") {
    const topic = options.topic.trim();
    if (topic) params.set("topic", topic);
  }
  return `/agora?${params.toString()}`;
}

/**
 * Headline copy for the share-CTA strip. Centralized here so the
 * mobile sticky bar and desktop inline panel render identical wording
 * (and so future copy A/B tests have a single edit point).
 *
 * Source: GOAL_FOUNDER.md "every shared link is an acquisition unit"
 * + AGORA_PLAN §pricing (free tier = 3 debates/day).
 */
export const SHARE_CTA_HEADLINE = "Begin your own agon" as const;
export const SHARE_CTA_SUBLINE = "3 free debates today" as const;
export const SHARE_CTA_BUTTON_LABEL = "Begin your own agon →" as const;

/**
 * Social-proof strip rendered near the topic. The "26 minds" figure
 * mirrors the live ALLOWED_SLUGS roster size; if the roster grows past
 * 26, this string should be updated in a single place. The kept wording
 * is deliberately tight: ~50 chars so it doesn't crowd the topic.
 */
export const SHARE_SOCIAL_PROOF_LINE =
  "Generated by Consult The Dead — 26 minds, infinite debates" as const;
